version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: chat-postgres
    environment:
      POSTGRES_DB: chatBD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 192837465
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: chat-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatBD
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 192837465
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: chat-photos
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
