spring:
  profiles:
    active: dev  # если сторонний юзер - запускать prod
    //todo апликейшен убнрат, оставить докер компос. Депенд он в докере. ПОчитать зачем 
    //локал хост. Network почитать. Как это работает. Правила гет пост, что можно предавать
    //в тело запроса. Протестировать @transction чтобы и в бд откатывалось