spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatBD
    username: postgres
    password: 192837465
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: chat-photos