spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

minio:
  bucketName: chat-photos
